name: CI
# Workflow file for windows
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    name: test-ubuntu
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake

      - name: Running cmake 
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake ..
      
