name: CI
# Workflow file for windows
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  Windows:
    name: build-windows
    runs-on: [ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Install dependencies
    - run: |
      sudo apt-get update
      sudo apt-get install ninja-build cmake
      ninja --version
      make --version
      gcc --version

    - name: Running cmake (windows)
      run: |
        cd ${{ github.workspace }}
        mkdir build
        cd build
        cmake ..
      
